const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    MAIN: 'MAIN',
    DEC_METODO:'DEC_METODO',
    IF:'IF',
    IFCE:'IFCE',
    ELSEIF:'ELSEIF',
    IFCEIF:'IFCEIF',
    WHILE:'WHILE',
    TOLOWER:'TOLOWER',
    TOUPPER:'TOUPPER',
    TRUNCATE:'TRUNCATE',
    ROUND: 'ROUND',
    TYPEOF:'TYPEOF',
    LENGTH:"LENGHT",
    

}
module.exports = TIPO_INSTRUCCION;