const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    MAIN: 'MAIN',
    DEC_METODO:'DEC_METODO',
    IF:'IF',
    IFCE:'IFCE',
    ELSEIF:'ELSEIF',
    IFCEIF:'IFCEIF',
    WHILE:'WHILE',
    

}
module.exports = TIPO_INSTRUCCION;