
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RTitulo = 15;
  public static final int cadenas = 19;
  public static final int RMain = 3;
  public static final int RGB = 7;
  public static final int Rvoid = 2;
  public static final int coma = 16;
  public static final int allave = 6;
  public static final int pcoma = 10;
  public static final int REjex = 11;
  public static final int decimales = 18;
  public static final int RValores = 12;
  public static final int pabre = 4;
  public static final int cllave = 8;
  public static final int pcierra = 5;
  public static final int RTituloY = 14;
  public static final int RTituloX = 13;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RGP = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Rvoid",
  "RMain",
  "pabre",
  "pcierra",
  "allave",
  "RGB",
  "cllave",
  "igual",
  "pcoma",
  "REjex",
  "RValores",
  "RTituloX",
  "RTituloY",
  "RTitulo",
  "coma",
  "RGP",
  "decimales",
  "cadenas"
  };
}

